name: Deploy to GCE
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CRED }}'
        
      - id: 'comput-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        with: 
          instance_name: 'instance-20240528-100722'
          zone: 'us-central1-c'
          ssh_private_key: '${{ secrets.C_KEY}}'
          command: 'echo hello oooo'
          
