name: Deploy to GCE
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        command_timeout: 30m
        script: | 
          echo "login in to server successfully"
    - name: deploying to server
      uses: actions/checkout@main
    - name: dockerize  
      run: docker compose up
          
